GET http://localhost:3000

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "MarioT97",
    "password": "Password123"
} 

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "mariot7",
    "password": "Password12"
} 